Sb 62 load data dynamo db
BFT-Smartbus/smartbus-heartbeat pull request #11
Opened 2022-12-30 19:31 UTC by StudentCZ

https://virgl.atlassian.net/jira/software/projects/SB/boards/1?selectedIssue=SB-62

Create dummy heartbeat json file that has 60 heartbeats record split by 3 different userId. Loading all data To Dynamodb heartbeat table.

2022-12-31 01:03 UTC, yhus commented on dynamodb_loader.py
> +with open('heartbeat_data.json') as json_file:
Constant/settings

2022-12-31 01:03 UTC, yhus commented on dynamodb_loader.py
> +    data = load(stream, Loader=Loader)
Also, what happens if this fails to load?

2022-12-31 01:03 UTC, yhus commented on dynamodb_loader.py
> +  #loop over the heartbeat list, and write all heartbeat data to dynamoDB heartbeat table.
You're describing what you're doing, which is decently obvious from reading the code.

Remember, comments should generally explain why you're doing something

2022-12-31 17:42 UTC, StudentCZ commented on dynamodb_loader.py
> +try:
The reason why we have it is from documentation, we were following the documentation syntax but after playing around with it, we don't really need the Cloader, try/except for our code to work. Unless I am wrong, if so please let me know

2023-01-02 05:25 UTC, chunloy requested changes
Please run `pip3 freeze > requirements.txt` any time you install new libraries.

2023-01-02 05:25 UTC, chunloy commented on dynamodb_loader.py
> +try:
This try/except block looks rather complex. Try the following instead:

```py 
import yaml

with open('settings.yaml', 'r') as stream:
    settings = yaml.safe_load(stream)
```

2023-01-03 18:02 UTC, StudentCZ commented on dynamodb_loader.py
> +try:
We made the change.

2023-01-03 18:22 UTC, StudentCZ commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
What exactly do we need to factor out here? I am confused.

2023-01-03 18:22 UTC, StudentCZ commented on dynamodb_loader.py
> +    data = load(stream, Loader=Loader)
Also we changed data to settings

2023-01-03 18:26 UTC, StudentCZ commented on dynamodb_loader.py
> +with open('heartbeat_data.json') as json_file:
Do you want us to factor out heartbeat as a constant for line 18 and put it into yml file? What about line 21 exactly do you want us to factor out? the word json_file and/or heartbeat_data.json?

2023-01-03 19:22 UTC, chunloy approved these changes
Looks good

2023-01-04 19:58 UTC, StudentCZ commented on dynamodb_loader.py
> +  #loop over the heartbeat list, and write all heartbeat data to dynamoDB heartbeat table.
We got rid of the comments.

2023-01-04 20:04 UTC, StudentCZ commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
How do you factor out a file name into setting.yaml

2023-01-04 20:07 UTC, yhus commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
The same way you factor out any other string. There's nothing special about it

2023-01-04 20:09 UTC, yhus commented on dynamodb_loader.py
> +with open('heartbeat_data.json') as json_file:
In general, you factor out all magic string and numerical values. In this case, heartbeat_data.json'

'I'm not sure how you'd factor out json_file, since it's just a variable name

2023-01-04 20:14 UTC, chunloy commented on dynamodb_loader.py
> +  #loop over the heartbeat list, and write all heartbeat data to dynamoDB heartbeat table.
I think comments are still helpful, just focus on explaining the why instead of the what and keep it simple. On line 19 you're converting types to ones that dynamoDB accepts. So your comment could be: # processing heartbeat data for dyanmoDB

On line 22 you're writing to dynamo, so the comment could be: # write heartbeat data to dynamoDB

2023-01-04 20:14 UTC, StudentCZ commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
with open('settings.yaml', 'r') as stream:
    settings = yaml.safe_load(stream)

These two lines of code are connected. I can't use settings to grab the data from settings.yaml without "with open('settings.yaml', 'r') as stream:" being first. It won't work if I factor 'settings.yaml' into settings[FILE_NAME] because settings has not been initialized yet.

2023-01-04 20:19 UTC, yhus commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
Ah, I missed that. In this case, just factor it out to a constant. There are some other ways to do this, but this is the simplest way

2023-01-04 20:20 UTC, yhus commented on dynamodb_loader.py
> +with open('heartbeat_data.json') as json_file:
Same for the table name btw. Remember, there should be NO magic values/numbers in your code, otherwise it's not really clean code

2023-01-04 20:38 UTC, StudentCZ commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
How does this look now? I think this is what you wanted.
<img width="987" alt="Screen Shot 2023-01-04 at 3 37 14 PM" src="https://user-images.githubusercontent.com/94021143/210645380-64c3faf0-c03e-4c5c-a68d-9e025e2052d5.png">
<img width="987" alt="Screen Shot 2023-01-04 at 3 37 29 PM" src="https://user-images.githubusercontent.com/94021143/210645385-1ec8afb1-34f1-4a19-b09f-f5575e88ffc7.png">

2023-01-04 21:55 UTC, chunloy commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
Referring to lines 6-7 in the first screenshot: I think Scott meant to declare a constant at the top of the dynamodb_loader.py file. It would look something like this:

```py
# imports
# ...
# ...
SETTINGS = 'settings.yaml'
```

Also, from what I understand, it's better practice to use `with open()` instead of `open()`. When you open a file, you want to make sure to close it after reading/writing. `with open()` will take care of closing for you, but `open()` will not.

2023-01-05 20:48 UTC, StudentCZ commented on dynamodb_loader.py
> +with open("settings.yaml", "r") as stream:
Like This ? 
<img width="1440" alt="Screen Shot 2023-01-05 at 3 47 53 PM" src="https://user-images.githubusercontent.com/94021143/210877061-5b0a9ac3-7578-41bc-95de-dddbcf3c1139.png">

2023-01-05 21:09 UTC, chunloy approved these changes
Looks good! Would like to see more comments e.g. converting heartbeat data and writing to tables. We can handle that later.

2023-01-05 23:08 UTC, tonyxuan2021 approved these changes
Good job Chao. You have addressed every comment.

2023-01-05 23:35 UTC, merged