Sb 62 heartbeat to lambda
BFT-Smartbus/smartbus-heartbeat pull request #9
Opened 2022-12-29 17:38 UTC by StudentCZ

https://virgl.atlassian.net/jira/software/projects/SB/boards/1?selectedIssue=SB-62

Created a DynamoDB table called heartbeat AWS.

2022-12-29 17:44 UTC, tonyxuan2021 approved these changes
Looking good! I don't have comment. I see a table has been created. good job!

2022-12-29 21:15 UTC, yhus requested changes
I'd strongly recommend factoring out setting specific values out to a separate settings file, or ideally, a .yaml

2022-12-29 21:15 UTC, yhus commented on package.json
> +{
Why is this required for a python project? Is this for serverless?

2022-12-29 21:15 UTC, yhus commented on package.json
> +  "description": "Example of a Python Flask API service with traditional Serverless Framework",
This needs to be updated

2022-12-29 21:15 UTC, yhus commented on create_table.py
> +    region_name="us-east-1",
Factor out to constant

2022-12-29 21:15 UTC, yhus commented on create_table.py
> +    endpoint_url="https://dynamodb.us-east-1.amazonaws.com/",
Constant

2022-12-29 21:15 UTC, yhus commented on create_table.py
> +    TableName="heartbeat",
Constant

2022-12-29 21:15 UTC, yhus commented on create_table.py
> +    ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
Constants

2022-12-29 21:17 UTC, yhus commented on .gitignore
> -__pycache__
Why is pycache removed?

2022-12-29 21:21 UTC, StudentCZ commented on package.json
> +{
This is for running the serverless command.

2022-12-29 21:50 UTC, StudentCZ commented on package.json
> +  "description": "Example of a Python Flask API service with traditional Serverless Framework",
Can you clarify exactly what needs to be updated?

2022-12-29 21:52 UTC, StudentCZ commented on create_table.py
> +    region_name="us-east-1",
Sorry, I have no idea what you mean by factor out to constant? Can you please clarify. Thank you.

2022-12-29 22:04 UTC, StudentCZ commented on .gitignore
> -__pycache__
accident. Will fix this.

2022-12-29 22:16 UTC, StudentCZ commented on package.json
> +{
If this is about package.json. We need these devDependencies.

2022-12-30 08:11 UTC, yhus requested changes

2022-12-30 08:11 UTC, yhus commented on create_table.py
> +
A lot of extra spaces here... forgot to clean up?

2022-12-30 08:11 UTC, yhus commented on create_table.py
> +app = Flask(__name__)
Didn't catch this earlier for some reason. Why does this module need to be a flask app? I don't see anything in here related to flask

2022-12-30 08:11 UTC, yhus commented on create_table.py
> +table = dynamodb.create_table(
What if the table is already created? Do you get an error here (if so, how do you handle it)? Will it just automatically drop the previous table and create a new one (in which case it's extremely dangerous)

2022-12-30 18:32 UTC, StudentCZ commented on create_table.py
> +app = Flask(__name__)
I made new changes and got rid of it

2022-12-30 18:33 UTC, StudentCZ commented on create_table.py
> +
We have cleaned up the code and no longer have comments. please review again thanks.

2022-12-30 18:34 UTC, StudentCZ commented on create_table.py
> +table = dynamodb.create_table(
We have tested this and we can't create another table with the same name. It will throw an error saying Table already exist.

2023-01-02 05:28 UTC, chunloy commented on app.py
> +] = f"postgresql://{USERNAME}:{PASSWORD}@localhost:5433/heartbeat"
Out of curiosity, why the port?

2023-01-02 05:34 UTC, chunloy requested changes
please run `pip3 freeze > requirements.txt`

2023-01-02 05:59 UTC, StudentCZ commented on app.py
> +] = f"postgresql://{USERNAME}:{PASSWORD}@localhost:5433/heartbeat"
This is the location for my postgresql port. I forgot to change it back to the default one

2023-01-02 07:26 UTC, yhus commented on create_table.py
> +table = dynamodb.create_table(
In this case you should surround this with a try catch block, and handle error(s).

A bit overkill in this specific scenario, but something that is good to get used to.

2023-01-03 17:33 UTC, StudentCZ commented on create_table.py
> +table = dynamodb.create_table(
I created a try and except for the create table.

2023-01-03 18:32 UTC, chunloy commented on app.py
>      "SQLALCHEMY_DATABASE_URI"
Didn't catch this before. Do we still need this connection string if we're moving to Lambda? Let' address this in another PR.

2023-01-03 18:35 UTC, chunloy approved these changes
LGTM

2023-01-03 18:52 UTC, yhus approved these changes

2023-01-03 18:52 UTC, yhus commented on create_table.py
> +    print("unable to create dynamodb table from create_table.py line 24")
I think this is a bit too specific. (We'll get into why when we start talking about logging)

Maybe something like - unable to create dynamo table <table_name>

Then when you catch the exception, print the exception message as well, e.g.: https://stackoverflow.com/questions/4690600/python-exception-message-capturing

2023-01-03 19:04 UTC, StudentCZ commented on create_table.py
> +    print("unable to create dynamodb table from create_table.py line 24")
Made the requested change. Please review again

2023-01-03 19:51 UTC, merged